### ISSUE TITLE
'distance' field was gone away

### ISSUE THREAD

**Issue by kidlab** [geokit/geokit-rails#56]
I'm using geokit-rails 2.0.1. When I run:

``` ruby
Location.within(5, origin: [37.792,-122.393]).order("distance asc")
```

An error occurred:

```
PG::UndefinedColumn: ERROR:  column "distance" does not exist
```

Why does the field `distance` go away?

**Comment by dmastylo** [comment]
I did some quick benchmarks looks like for 1000 iterations sorting the objects post-query via Ruby only increases execution time by (an average) 1/10th of a second.

```
measure = Benchmark.measure { 1000.times { Venue.within(5, origin: origin).sort_by { |v| v.distance_to(origin)  } } }
```
*=> #<Benchmark @real=1.487982, @cstime=0.0, @cutime=0.0, @stime=0.5699999999999994, @utime=0.7400000000000002, @total=1.3099999999999996>*

```
Benchmark.measure { 1000.times { Venue.within(5, origin: origin) } }
```
*=> #<Benchmark @real=1.428282, @cstime=0.0, @cutime=0.0, @stime=0.5799999999999992, @utime=0.6799999999999997, @total=1.259999999999999> *

**Comment by aandis** [comment]
@kidlab thanks! works great.

**Comment by bkmediagroup-josh** [comment]
@kidlab I had some issues with your solution. When calling .count, bad SQL is generated as it tries to wrap the select clause in a COUNT(). The pluck method wipes out generated distance column. This is definitely not a criticism of your solution, just wanted to document my issues for future users. As of version 2.1.0, the solution for sorting by distance for me was to use geokit's by_distance method. It requires specifying an origin which is a bit redundant after having already provided one in the call to within, but the result was exactly what I was looking for.

**Comment by jamsi** [comment]
Wondering why this isn't in master yet? Went to create a new Rails project and took me awhile to realise that I didn't have @kidlab's "within" override in an initializer (my other rails projects already did).

**Comment by man-trifork** [comment]
How can I use @kidlab 's patch?

**Comment by sandergarretsen** [comment]
For all people (like me) hitting this thread, searching for a way  to order results by distance with this Gem. 
This thread (and all linked issues) might give the impression that its not supported _at all_ to order results by distance,  for the reason of lacking a "distance" field. 

Which is not true:

although (from OP)...

`Location.within(5, origin: [37.792,-122.393]).order("distance asc")`

...will not work because of the absence of the "distance" field, Like @bkmediagroup-josh metioned. Using the provided `by_distance` scope works fine. So the equivalent would be: 

`Location.within(5, origin: [37.792,-122.393]).by_distance(origin:  [37.792,-122.393])`

Not sure about the internals and optimizations. 
But I just wanted to point out that this feature is provided as a custom scope, which is actually documented fine, but might be easy to miss.

**Comment by kidlab** [comment]
Indeed, @sandergarretsen and @bkmediagroup-josh are correct, using `by_distance` should be the solution.
